- name: Deploy website using Ansible
  hosts: apache
  become: true

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Set ownership for web directory
      file:
        path: /var/www/html
        owner: ubuntu
        group: ubuntu
        mode: '0755'
        recurse: yes

    - name: Deploy website files
      synchronize:
        src: .
        dest: /var/www/html
        delete: yes
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=inventory.ini"
          - "--exclude=deploy.yml"
          - "--exclude=Jenkinsfile"
