---
- name: Deploy website using Ansible
  hosts: web
  become: yes

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Remove default Apache page
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Copy index.html from Jenkins
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Copy image file from Jenkins
      copy:
        src: image.png
        dest: /var/www/html/image.png
        owner: www-data
        group: www-data
        mode: '0644'
